# NAME|SSH_HOST|LOCAL_PATH|S3_PATH|DATE

wspace|192.168.100.71|/mnt/nfs_share/wspace-backup/base_backup/done|s3://backup-app.wspace.ph/base_backup|20261002
urbanity|192.168.100.69|/mnt/nfs_share/urbanity-backup/base_backup/done|s3://backup-ws.urbanity.ph/base_backup|20261003
happywell|192.168.100.64|/home/pg-backup/base_backup.d/done|s3://backup-happywell/base_backup|20261007
landev|192.168.100.61|/home/pg-backup/base_backup.d/done|s3://backup-landev/base_backup|20261007
mmgi|192.168.100.65|/home/backup/base_backup/done|s3://backup-mmgi/base_backup|20261003
picar|192.168.100.67|/mnt/nfs_share/picar-backup/base_backup/done|s3://backup-picar/base_backup|20261007
rockwell|club-server|/home/pg-backup/base_backup.d/done|s3://backup-rockwell/base_backup|20261001
tldc|192.168.100.63|/mnt/nfs_share/tldc-backup/base_backup/done|s3://backup-tldc/base_backup|20261003
IMS|192.168.100.77|/var/lib/postgresql/pg-backup/base_backup.d/done|s3://casi-db-backups/ims/base_backup|20261003
WIKI|192.168.100.11|/home/backup/base_backup/done|s3://casi-db-backups/wiki/base_backup|20261001
